
[functions.gmail-scan]
enabled = true
verify_jwt = false
import_map = "./functions/gmail-scan/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gmail-scan/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gmail-scan/*.html" ]

[functions.gmail-scan-fetch-body]
enabled = true
verify_jwt = true
import_map = "./functions/gmail-scan-fetch-body/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gmail-scan-fetch-body/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gmail-scan-fetch-body/*.html" ]

[functions.gmail-scan-stream]
enabled = true
verify_jwt = true
import_map = "./functions/gmail-scan-stream/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gmail-scan-stream/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gmail-scan-stream/*.html" ]
